In [2]:
import pandas as pd

In [3]:
FILEPATH='../data/pims_cloudpbx_cdrua_201806061020.csv'

In [4]:
df = pd.read_csv(FILEPATH,sep='\t')

In [21]:
df['len']= df['ua'].apply(lambda x: len(x) if type(x) is str else 0)
df[df['len']<6]

        id     ua  len
0        3    NaN    0
1     3802      !    1
2     3684  '-=-'    5
5     3777      +    1
6     3537     ++    2
7     3782      1    1
8     2648    205    3
32    4063  66.71    5
34    3502      a    1
38    4076   A1B2    4
127   2987   Acme    4
324   3535      b    1
325   3761   Back    4
653   3669    BSL    3
657   3958   CAll    4
662   4054  China    5
665   3482  Cisco    5
765   3874    ddd    3
2892  3821   FPBX    4
2962  3621   free    4
3179  4028  Hello    5
3187  3574      i    1
3191  3773    IOS    3
3194  3600     ip    2
3280  3983  marco    5
3286  3372   meaw    4
3292  2860  Mitel    5
3306   345    MS1    3
3320  3503      o    1
3381   255    PBX    3
3382  3774    pes    3
3655  3332  QWEST    5
3659  3515      s    1
3660  4034    SBC    3
3665  3489    SIP    3
3677  3106   Sipp    4
3687  4047   snom    4
3699  3939   SPIP    4
3705  4073  Tele2    5
3709  3955   test    4
3711  3885     tr    2
3724  3577    USA    3
3726  3147   user    4
3739   301   VCSR    4
3745   205  VMAIL    5
3747   771   Voip    4
3757  3878    vpn    3
3758  1894    VVS    3
3767  3514      x    1
3870  3368  xlite    5
3871  3645   xnxx    4
3872  3646  xnxxZ    5
3999  3967      Z    1
4082  4009    ZTE    3